import type { Metadata } from "next";
import "./globals.css";
import {
  geistSans, geistMono, inter, playfair,
  nunito, poppins, cairo, notoNaskh,
  amiri, imperial, reemKufi, lemonada,
  tajawal, almarai,
} from "../lib/fonts";
import HtmlLangSync from "@/components/Htmllangsync";
import { I18nProvider } from "@/lib/i18n";


export const metadata: Metadata = {
  title: "English Sahla With Khawla",
  description: "Generated by Mat95rix7",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`
        ${geistSans.variable}
        ${geistMono.variable}
        ${inter.variable}
        ${poppins.variable}
        ${playfair.variable}
        ${nunito.variable}
        ${cairo.variable}
        ${notoNaskh.variable}
        ${amiri.variable}
        ${imperial.variable}
        ${reemKufi.variable}
        ${lemonada.variable}
        ${tajawal.variable}
        ${almarai.variable}
        h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <I18nProvider>
          <HtmlLangSync />
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}